import type { PluginState } from '@/types'
import type { AtlasConfig } from '@/config/schema'
export type { AgentDefinition, PluginState, EchoLevel, AgentMode } from '@/types'
export type { AtlasConfig, AgentPresetConfig, AgentPresetsMap, AthenaConfig, SkillsConfig, CandidatesConfig, CuratorConfig } from '@/config/schema'
export { loadConfig } from '@/config/loader'
export { DEFAULT_CONFIG } from '@/config/schema'
export { handleSystemTransform, buildAllSystemSections } from '@/hooks/system-transform'
export { buildEchoPrompt, buildDisabledPrompt } from '@/modules/echo/prompt-builder'
export { shouldDisableEcho } from '@/modules/echo/auto-clarity'
export { buildFullVaultPrompt, buildMemoryToolsPrompt } from '@/modules/vault/memory-protocol'
export { handleToolBefore, handleRealToolBefore } from '@/hooks/tool-before'
export { handleToolAfter, handleRealToolAfter, compressToolResult } from '@/hooks/tool-after'
export { shouldCompressResult, compressBashResult, compressToolResult as compressForgeToolResult } from '@/modules/forge/bash-wrapper'
export { getForgeStats, resetRedundancyCache } from '@/modules/forge/compressor'
export { compressErrors } from '@/modules/forge/error-compressor'
export { compressDifferential, clearDiffCache, getDiffCacheSize } from '@/modules/forge/diff-cache'
export { compressReadResult, clearReadCache, getReadCacheSize } from '@/modules/forge/read-cache'
export { handleCompacting, buildCompactionContext } from '@/hooks/compacting'
export { handleEvent, handleChatMessage, handleRealEvent } from '@/hooks/event-handler'
export { handleEchoCommand, handleVerboseCommand, isAtlasCommand, ECHO_COMMAND, VERBOSE_COMMAND } from '@/modules/echo/commands'
export { stripPrivateTags } from '@/modules/vault/memory-protocol'
export { initializeVault, ensureSession } from '@/modules/vault/session-manager'
export { vaultSaveObservation, vaultSaveMemory } from '@/modules/vault/client'
export { handleMemSearch, handleMemTimeline, handleMemGetObservation, handleMemSave } from '@/modules/vault/tool-handlers'
export type { MemToolResult } from '@/modules/vault/tool-handlers'
export { runCodexIndex } from '@/modules/codex/codex'
export { handleCodexSearch, handleCodexReindex } from '@/modules/codex/tool-handlers'
export { buildCodexPrompt, buildCodexContextPrompt } from '@/modules/codex/prompt'
export { initializeCodex } from '@/modules/codex/initializer'
export { buildDependencyGraph } from '@/modules/codex/graph-builder'
export { writeGraphHtml } from '@/modules/codex/graph-renderer'
export type { CodexConfig, IndexedFile, ImportRef, FileType, GraphNode, GraphEdge, DependencyGraph, IndexStats } from '@/modules/codex/types'
export { getDefaultSkillsPaths, ensureSkillsDirectory, loadManifest, saveManifest, createDefaultManifest, getAthenaConfigDefaults, resolveSkillsPaths, isSkillsEnabled, findSkillById, updateSkillInManifest, addSkillToManifest, removeSkillFromManifest, getSkillContentPath, skillContentExists, deleteSkillContent } from '@/modules/athena/skills/storage'
export { handleListSkills, handleViewSkill, handleManageSkill } from '@/modules/athena/skills/tool-handlers'
export type { SkillStatus, SkillDefinition, SkillManifest, SkillsStoragePaths, SkillListFilter, ListSkillsOptions, ViewSkillOptions, ManageSkillOptions, SkillToolResult } from '@/modules/athena/skills/types'
export type { AthenaStats, SkillsStats, CandidatesStatsSummary, CuratorStats } from '@/modules/athena/skills/stats'
export { runCurator as runSkillsCurator, getCuratorStatus as getSkillsCuratorStatus, setCuratorPaused as setSkillsCuratorPaused, touchSkill as touchSkillForUsage, togglePinned as toggleSkillPinned, isCuratorPaused as isSkillsCuratorPaused, runCuratorReview as runCuratorReviewAnalysis, loadCuratorReview as loadCuratorReviewReport } from '@/modules/athena/skills/curator'
export type { CuratorRunResult, CuratorStatusResult, CuratorReviewResult, CuratorReviewReport } from '@/modules/athena/skills/curator'
export { buildAthenaStats, formatAthenaStats, getStatsSummary } from '@/modules/athena/skills/stats'
export { analyzeToolExecution, persistCandidates, recordToolExecution, handleListCandidates, getCandidatesConfig, isCandidatesEnabled } from '@/modules/athena/candidates/detector'
export { getCandidatesBasePath, getCandidatesFilePath, ensureCandidatesDirectory, loadCandidatesManifest, saveCandidatesManifest, createDefaultCandidatesManifest, getOrCreateCandidatesManifest, findCandidateById, upsertCandidate, removeExpiredCandidates, enforceMaxCandidates, filterCandidatesByOptions, getSessionToolCallCount, incrementSessionToolCallCount, resetSessionToolCallCount } from '@/modules/athena/candidates/storage'
export type { CandidateStatus, CandidateEvidence, CandidateEvidenceReason, SkillCandidate, CandidatesManifest, CandidatesStats, ListCandidatesOptions, CandidatesToolResult } from '@/modules/athena/candidates/types'

export { createAtlasAgent } from '@/modules/agents/atlas'
export { createPathfinderAgent } from '@/modules/agents/pathfinder'
export { createArchivistAgent } from '@/modules/agents/archivist'
export { createElderAgent } from '@/modules/agents/elder'
export { createArtisanAgent } from '@/modules/agents/artisan'
export { createMenderAgent } from '@/modules/agents/mender'
export { createTribunalAgent } from '@/modules/agents/tribunal'
export { createInspectorAgent } from '@/modules/agents/inspector'
export { createScribeAgent } from '@/modules/agents/scribe'
export { createCuratorAgent } from '@/modules/agents/curator'
export { createSentinelAgent } from '@/modules/agents/sentinel'
export { createHeraldAgent } from '@/modules/agents/herald'
export { createLorekeeperAgent } from '@/modules/agents/lorekeeper'
export { createAlchemistAgent } from '@/modules/agents/alchemist'
export { createMagistrateAgent } from '@/modules/agents/magistrate'
export { createEnvoyAgent } from '@/modules/agents/envoy'
export { createQuartermasterAgent } from '@/modules/agents/quartermaster'
export { createTacticianAgent } from '@/modules/agents/tactician'
export { createSquireAgent } from '@/modules/agents/squire'
export { buildAgentRegistry, getAgentConfigs, AGENT_ALIASES } from '@/modules/agents/registry'
export type { AgentSdkConfig } from '@/modules/agents/registry'
export function createInitialState(config: AtlasConfig): PluginState { return { echoLevel: config.echo.defaultLevel, agentMode: config.agents.defaultMode, activePreset: config.agents.preset } }